name: arvivet_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  calendar_date_picker2: ^2.0.1
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_localizations: # â† adds translated Material strings, etc.
    sdk: flutter
  intl: 0.20.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/images/
  fonts:
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-Variable.ttf
